packages:
  - apps/**
  - packages/**

  # 2颗星代表匹配任意层级的子目录

onlyBuiltDependencies:
  - '@mui/x-telemetry'
  - '@nestjs/core'
  - '@scarf/scarf'
  - '@tailwindcss/oxide'
  - bcrypt
  - esbuild
  - puppeteer
  - unrs-resolver
