# One * matches a single directory level, while ** matches any nested directory levels.
packages:
  - apps/**
  - packages/**

onlyBuiltDependencies:
  - '@mui/x-telemetry'
  - '@nestjs/core'
  - '@scarf/scarf'
  - '@tailwindcss/oxide'
  - bcrypt
  - esbuild
  - puppeteer
  - unrs-resolver
