apiVersion: v1
kind: ConfigMap
metadata:
  name: aks-deploy-test-config
  namespace: namespace-workflow-1741789480081
  labels:
    app.kubernetes.io/name: aks-deploy-test
    kubernetes.azure.com/generator: devhub
data: