name: Delivery pipline

on:
  push:
    branches: main
    paths-ignore:
      - "**/.github/**"
      - "**/*.txt"
      - "**/*.MD"
      - "**/*.md"
  workflow_dispatch:
    inputs:
      environment:
        description: "The environment to deploy"
        required: true
        type: choice
        options: [uat, test]
        default: uat
      deployedApp:
        description: "The app to deployed"
        required: true
        type: choice
        options: [apps/auth, apps/security]
permissions:
  security-events: write
  actions: read
  contents: read
  issues: write

jobs:
  CICD-pipline:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Run shared delivery pipeline
        uses: aoda-zhang/shared-devops/.github/workflows/shared_delivery_pipline.yaml@master
        with:
          app_repository: ${{ github.repository }}
          app_branch: ${{ github.ref }}
          currentEnvironment: ${{ inputs.environment }}
          deployed_app: ${{ inputs.deployedApp }}
          deploye_type: "WEBAPP"
          config_path: ${{ inputs.deployed_app }}
          PAT: ${{ secrets.PAT }}
          AZURE_ACR_SERVER: ${{ secrets.AZURE_ACR_SERVER }}
          AZURE_ACR_USERNAME: ${{ secrets.AZURE_ACR_USERNAME }}
          AZURE_ACR_PASSWORD: ${{ secrets.AZURE_ACR_PASSWORD }}
