name: Deployment-pipiline
on:
  # Only auto deploy when push to develope branch
  # push:
  #   branches: develope
  #   paths-ignore:
  #     - "**/.github/**"
  #     - "**/*.txt"
  #     - "**/*.MD"
  #     - "**/*.md"
  workflow_dispatch:
    inputs:
      deployedEnvironment:
        description: "The environment to deploy"
        required: true
        type: choice
        options: [uat, test]
        default: uat
      deployedApp:
        description: "The app name to deploy"
        required: true
        type: choice
        options: [apps/auth, apps/security]

permissions:
  security-events: write
  actions: read
  contents: read
  issues: write

jobs:
  Deployment-pipiline:
    uses: aoda-zhang/shared-devops/.github/workflows/shared_delivery_pipline.yaml@master
    with:
      app_repository: ${{ github.repository }}
      app_branch: ${{ github.ref }}
      deployed_app: ${{ inputs.deployedApp }}
      deploye_type: WEBAPP
      config_path: ${{inputs.deployedApp}}
      currentEnvironment: ${{inputs.deployedEnvironment}}
    secrets:
      PAT: ${{ secrets.PAT }}
      DOCKER_SERVER: ${{ secrets[format('DOCKER_SERVER_{0}', inputs.deployedEnvironment)] }}
      DOCKER_USERNAME: ${{ secrets[format('DOCKER_USERNAME_{0}', inputs.deployedEnvironment)] }}
      DOCKER_PASSWORD: ${{ secrets[format('DOCKER_PASSWORD_{0}', inputs.deployedEnvironment)] }}
