name: Deploy to Azure AKS

on:
  push:
    branches: main
    paths-ignore:
      - "**/.github/**"
      - "**/*.txt"
      - "**/*.MD"
      - "**/*.md"
  workflow_dispatch:
    inputs:
      environment:
        description: "The environment to deploy"
        required: true
        type: choice
        options: [UAT, TEST]
        default: UAT
      AppName:
        description: "The app name to deploy"
        required: true
        type: choice
        options: [Auth, Security]
permissions:
  security-events: write
  actions: read
  contents: read
  issues: write

jobs:
  Stage1:
    uses: aoda-zhang/shared-devops/.github/workflows/project_prepare.yaml@master
    with:
      app_repository: ${{ github.repository }}
      app_branch: ${{ github.ref }}
      app_folder_path: Apps/${{inputs.AppName}}
      config_folder_path: fullStack-frontEnd/${{inputs.AppName}}
      currentEnvironment: ${{ inputs.environment || 'UAT'}}
    secrets:
      PAT: ${{ secrets.PAT }}

  Stage2:
    needs: [Stage1]
    uses: aoda-zhang/shared-devops/.github/workflows/image_build.yaml@master
    with:
      app_branch: ${{ github.ref }}
      app_folder_path: Apps/${{inputs.AppName}}
      currentEnvironment: ${{ inputs.environment || 'UAT'}}
    secrets:
      AZURE_ACR_SERVER: ${{ secrets.ACR_SERVER_UAT }}
      AZURE_ACR_USERNAME: ${{ secrets.ACR_USERNAME_UAT }}
      AZURE_ACR_PASSWORD: ${{ secrets.ACR_PWD_UAT }}
