name: Release-pipiline （Prod）
on:
  # For Prod,Only Manuly deploy
  workflow_dispatch:
    inputs:
      deployedApp:
        description: 'The app name to deploy'
        required: true
        type: choice
        options: [apps/auth, apps/security]

permissions:
  security-events: write
  actions: read
  contents: read
  issues: write

jobs:
  Deployment-pipiline:
    uses: aoda-zhang/shared-devops/.github/workflows/shared_delivery_pipline.yaml@master
    with:
      app_repository: ${{ github.repository }}
      app_branch: ${{ github.ref }}
      deployed_app: ${{ inputs.deployedApp }}
      deploye_type: WEBAPP
      config_path: ${{inputs.deployedApp}}
      currentEnvironment: prod
    secrets:
      PAT: ${{ secrets.PAT }}
      DOCKER_SERVER: ${{ secrets.DOCKER_SERVER_PROD }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME_PROD }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD_PROD }}
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS_PROD }}
      AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP_PROD }}
      AKS_CLUSTER_NAME: ${{ secrets.AKS_CLUSTER_NAME_PROD }}
      AKS_NAMESPACE: ${{ secrets.AKS_NAMESPACE_PROD }}
